gui:
  showBottomLine: true
  nerdFontsVersion: "3"
  showFileIcons: true
  showRandomTip: false
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
disableStartupPopups: false
notARepository: 'skip'
keybinding:
  universal:
    prevItem: 'k'
    nextItem: 'j'
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevBlock: '<C-k>'
    nextBlock: '<C-j>'
    extrasMenu: '@'
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'
  commits:
    moveDownCommit: ''
    moveUpCommit: ''
os:
  editPreset: 'nvim'
